POST https://discord.com/api/v9/channels/641351235215294486/messages
Authorization: Nzc4NTM1ODEzNDM2MTQ1Njk2.YcgVlw.6Rr0qHMUHWdI0CjedkvdVA9Dbu4
Content-Type: application/json

{"content":"<@!300506208832585728> thank you","nonce":"923027088506617856","tts":false}